Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -19,9 +19,13 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        python -m pip install pylint
+        python -m pip install pylint pylint-exit
     - name: List Directory
       run: find .
     - name: Analysing the code with pylint
       run: |
-        pylint `find . |grep .py$ | xargs`
+        pylint `find . |grep .py$ | xargs` || pylint-exit $?
+        if [ $? -ne 0 ]; then
+          echo "An error occurred while running pylint." >&2
+          exit 1
+        fi
